apiVersion: v1
kind: Namespace
metadata:
  name: ai-governor
  labels:
    name: ai-governor
    app.kubernetes.io/name: universal-ai-governor
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: namespace
  annotations:
    description: "Universal AI Governor deployment namespace"
