apiVersion: v2
name: universal-ai-governor
description: A Helm chart for Universal AI Governor - A comprehensive AI governance system
type: application
version: 1.0.0
appVersion: "1.0.0"

keywords:
  - ai
  - governance
  - llm
  - moderation
  - policy
  - guardrails
  - security

home: https://github.com/your-org/universal-ai-governor
sources:
  - https://github.com/your-org/universal-ai-governor

maintainers:
  - name: Universal AI Governor Team
    email: team@example.com
    url: https://github.com/your-org/universal-ai-governor

annotations:
  category: AI/ML
  licenses: MIT
  images: |
    - name: universal-ai-governor
      image: universal-ai-governor:1.0.0
    - name: postgres
      image: postgres:15-alpine
    - name: redis
      image: redis:7-alpine
    - name: elasticsearch
      image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0

dependencies:
  - name: postgresql
    version: "12.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
  - name: redis
    version: "18.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
  - name: elasticsearch
    version: "8.x.x"
    repository: "https://helm.elastic.co"
    condition: elasticsearch.enabled
  - name: prometheus
    version: "25.x.x"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: monitoring.prometheus.enabled
  - name: grafana
    version: "7.x.x"
    repository: "https://grafana.github.io/helm-charts"
    condition: monitoring.grafana.enabled
